// agee configure — bake the gateway into the extension so it works on load.
//
// Writes extension/agee.config.json (git-ignored) with the gateway URL and token.
// The token is a secret: this script reads it but never prints it. The URL is
// safe and is shown for confirmation.
//
// Token source, in order:
//   1. MOA_GATEWAY_TOKEN in the environment (CI / explicit override)
//   2. the main machine over SSH (reclaim@10.147.17.10), read from its .env
//
// URL override: AGEE_GATEWAY_URL (defaults to the live gateway).
//
// Run:  npm run configure
//       AGEE_GATEWAY_URL=http://host:port npm run configure

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(new URL("..", import.meta.url).pathname);
const outFile = join(root, "extension", "agee.config.json");

const GATEWAY_URL = (process.env.AGEE_GATEWAY_URL || "http://10.147.17.10:8788").replace(/\/+$/, "");
const MODEL = process.env.AGEE_MODEL || "claude-opus-4-8";
const SSH_TARGET = process.env.AGEE_SSH_TARGET || "reclaim@10.147.17.10";
const SERVICE = process.env.AGEE_SERVICE || "moa-gateway.service";
const REMOTE_ENV = process.env.AGEE_REMOTE_ENV || "/home/reclaim-ethiopia/moa-assistant/software/moa_gateway/.env";

function tokenFromEnv() {
  const t = (process.env.MOA_GATEWAY_TOKEN || "").trim();
  return t || null;
}

// Read the EFFECTIVE MOA_GATEWAY_TOKEN the live gateway uses, over SSH. The
// running service's env is authoritative (it may differ from .env when the
// systemd unit sets Environment= directly), so prefer that and fall back to
// .env. The value is captured into this process and written to disk; it is
// never logged.
function extractToken(text) {
  const m = String(text || "").match(/MOA_GATEWAY_TOKEN=("?)([^\s"']+)\1/);
  return m ? m[2] : null;
}

function tokenFromSsh() {
  const remote =
    `systemctl --user show -p Environment ${SERVICE} 2>/dev/null; ` +
    `grep -m1 '^MOA_GATEWAY_TOKEN=' ${REMOTE_ENV} 2>/dev/null || true`;
  try {
    const out = execFileSync(
      "ssh",
      ["-o", "BatchMode=yes", "-o", "ConnectTimeout=10", SSH_TARGET, remote],
      { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }
    );
    return extractToken(out);
  } catch {
    return null;
  }
}

function write(token) {
  const body = JSON.stringify(
    {
      _comment: "Generated by `npm run configure`. Git-ignored — holds the gateway token. Do not commit.",
      gatewayUrl: GATEWAY_URL,
      gatewayToken: token,
      model: MODEL,
    },
    null,
    2
  );
  writeFileSync(outFile, `${body}\n`, { mode: 0o600 });
}

const token = tokenFromEnv() || tokenFromSsh();

if (!token) {
  console.error("agee configure: could not find a gateway token.");
  console.error(`  Tried MOA_GATEWAY_TOKEN env and ${SSH_TARGET}:${REMOTE_ENV} over SSH.`);
  console.error("  Set MOA_GATEWAY_TOKEN and re-run, or fix SSH access to the main machine.");
  process.exit(1);
}

write(token);

console.log("agee configure: wrote extension/agee.config.json");
console.log(`  gateway URL : ${GATEWAY_URL}`);
console.log(`  model       : ${MODEL}`);
console.log(`  token       : set (${token.length} chars, not shown)`);
console.log("");
console.log("Next: load the extension once at chrome://extensions -> Load unpacked ->");
console.log(`      ${join(root, "extension")}`);
console.log("It is configured. No Options visit needed.");
